//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOP_Dashboard_CMS
{
    using System;
    
    public partial class sp_MPOP__Dashboard_VotingOpeningandClosing_Select_Result4
    {
        public string VotingTimeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
