//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOP_Dashboard_CMS
{
    using System;
    
    public partial class sp_MPOP__Dashboard_Contestant_Select_Result1
    {
        public string ContestantID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedData { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> VoteCount { get; set; }
        public string Remark { get; set; }
        public string ContestantNo { get; set; }
    }
}
