//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOP_Dashboard_CMS
{
    using System;
    
    public partial class sp_MPOP_Role_Select_Result2
    {
        public string RoleID { get; set; }
        public string RoleName { get; set; }
    }
}
