//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOP_Dashboard_CMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Dashboard_CMS_MyTelBillCharge
    {
        public string MyTelBillChargeID { get; set; }
        public string MSISDN { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
